base_dir: logs_stackoverflow_disc

data:
  batch_size: 32
  data_name: stackoverflow
  data_dir:  data/noise_so_std/{}.pkl
  num_samples_per_seq: 5

model:
  name: XFMRNHPFastDisc
  hidden_dim: 32
  time_emb_dim: 64
  num_heads: 1
  num_layers: 2
  dropout: 0.1
  sharing_param_layer: False
  use_ln: False
  mc_num_sample_per_step: 20
  pretrained_model_dir: logs_stackoverflow/XFMRNHPFast_20220727-20:40:05/models/saved_model
  sample_len: 20
  loss: bce

train:
  dropout_rate: 0.1
  lr: 0.0004
  epoch: 0
  max_epoch: 100